{% set name = "plum-dispatch" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum-dispatch-{{ version }}.tar.gz
  sha256: 0a3595f1d09843bc63d8b8365969e187b940d27f475ff1f5d1407d1ffad625d1

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=0.29
    - setuptools >=41
  run:
    - numpy >=1.16
    - python
    - six

test:
  imports:
    - plum
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
